# Generated by Django 2.2.4 on 2019-11-12 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('nombre', models.CharField(max_length=60)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('nombre', models.CharField(max_length=50)),
                ('maquina', models.CharField(max_length=10)),
                ('ancho_util', models.IntegerField()),
                ('largo_util', models.IntegerField()),
                ('ancho_lamina', models.IntegerField()),
                ('largo_lamina', models.IntegerField()),
                ('superficie', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
