# Generated by Django 3.1.1 on 2020-09-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_auto_20191112_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marco',
            name='ancho_lamina',
            field=models.IntegerField(verbose_name='Ancho Lamina (mm)'),
        ),
        migrations.AlterField(
            model_name='marco',
            name='ancho_util',
            field=models.IntegerField(verbose_name='Ancho útil (mm)'),
        ),
        migrations.AlterField(
            model_name='marco',
            name='largo_lamina',
            field=models.IntegerField(verbose_name='Largo Lamina (mm)'),
        ),
        migrations.AlterField(
            model_name='marco',
            name='largo_util',
            field=models.IntegerField(verbose_name='Largo Útil  (mm)'),
        ),
        migrations.AlterField(
            model_name='marco',
            name='superficie',
            field=models.FloatField(blank=True, null=True, verbose_name='Superfície'),
        ),
    ]
