# Generated by Django 2.2.4 on 2019-11-12 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('nombre', models.CharField(max_length=50)),
                ('precalentado', models.IntegerField()),
                ('moldeo', models.IntegerField()),
                ('enfriado', models.IntegerField()),
                ('espesor', models.IntegerField()),
                ('calefaccion', models.ImageField(upload_to='')),
                ('empujador', models.ImageField(upload_to='')),
                ('troquel', models.IntegerField()),
                ('altura_tupir', models.IntegerField()),
                ('observaciones', models.IntegerField()),
                ('marco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.Marco')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.Material')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
