# Generated by Django 2.2.4 on 2019-11-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0002_auto_20191112_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pieza',
            options={'ordering': ('pk',)},
        ),
    ]
