# Generated by Django 2.2.4 on 2019-11-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0004_pieza_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieza',
            name='espesor',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
