# Generated by Django 3.1.1 on 2020-09-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0005_auto_20191112_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieza',
            name='calefaccion',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Seteo Calefaccion'),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='empujador',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Imagen Empujador'),
        ),
    ]
