# Generated by Django 2.2.4 on 2019-11-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ('pk',)},
        ),
    ]
